version: '3.8'


services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    expose:
      - 5432
    networks:
      - main_network
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    networks:
      - main_network
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:

networks:
  main_network:

